<a href="https://colab.research.google.com/github/faizirana123/Lab-assignment/blob/main/25122_NB_Lab_Task_31_05_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score


In [79]:
df1 = pd.read_csv("Test_spam.csv", encoding='latin1')


In [80]:
df1

v1                                                 v2
0   spam  FreeMsg Hey there darling it's been 3 week's n...
1    ham  Even my brother is not like to speak with me. ...
2    ham  As per your request 'Melle Melle (Oru Minnamin...
3   spam  WINNER!! As a valued network customer you have...
4   spam  Had your mobile 11 months or more? U R entitle...
5    ham  I'm gonna be home soon and i don't want to tal...
6   spam  SIX chances to win CASH! From 100 to 20,000 po...
7   spam  URGENT! You have won a 1 week FREE membership ...
8    ham  I've been searching for the right words to tha...
9    ham                I HAVE A DATE ON SUNDAY WITH WILL!!
10  spam  XXXMobileMovieClub: To use your credit, click ...
11   ham                         Oh k...i'm watching here:)

In [81]:
df1['v1'] = df1.v1.map({'ham':0, 'spam':1})
df1

v1                                                 v2
0    1  FreeMsg Hey there darling it's been 3 week's n...
1    0  Even my brother is not like to speak with me. ...
2    0  As per your request 'Melle Melle (Oru Minnamin...
3    1  WINNER!! As a valued network customer you have...
4    1  Had your mobile 11 months or more? U R entitle...
5    0  I'm gonna be home soon and i don't want to tal...
6    1  SIX chances to win CASH! From 100 to 20,000 po...
7    1  URGENT! You have won a 1 week FREE membership ...
8    0  I've been searching for the right words to tha...
9    0                I HAVE A DATE ON SUNDAY WITH WILL!!
10   1  XXXMobileMovieClub: To use your credit, click ...
11   0                         Oh k...i'm watching here:)

In [82]:
X= df1['v2'].to_numpy()
Y = df1['v1'].to_numpy()
Y = Y.astype('int')


In [83]:
print("X")
print(X)
print("y")
print(Y)

X
["FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv"
 'Even my brother is not like to speak with me. They treat me like aids patent.'
 "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"
 'WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.'
 'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030'
 "I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."
 'SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info'
 'URGENT! You have won a 1 w

In [84]:
vec = CountVectorizer( )

In [85]:
vec.fit(X)
vec.vocabulary_

{'freemsg': 58,
 'hey': 70,
 'there': 140,
 'darling': 48,
 'it': 78,
 'been': 25,
 'week': 161,
 'now': 100,
 'and': 18,
 'no': 98,
 'word': 169,
 'back': 23,
 'like': 83,
 'some': 128,
 'fun': 62,
 'you': 174,
 'up': 150,
 'for': 56,
 'still': 132,
 'tb': 137,
 'ok': 103,
 'xxx': 172,
 'std': 131,
 'chgs': 35,
 'to': 144,
 'send': 125,
 '50': 10,
 'rcv': 117,
 'even': 55,
 'my': 94,
 'brother': 28,
 'is': 77,
 'not': 99,
 'speak': 130,
 'with': 165,
 'me': 85,
 'they': 141,
 'treat': 147,
 'aids': 16,
 'patent': 109,
 'as': 21,
 'per': 110,
 'your': 175,
 'request': 120,
 'melle': 86,
 'oru': 107,
 'minnaminunginte': 89,
 'nurungu': 101,
 'vettam': 157,
 'has': 66,
 'set': 126,
 'callertune': 31,
 'all': 17,
 'callers': 30,
 'press': 113,
 'copy': 42,
 'friends': 59,
 'winner': 164,
 'valued': 155,
 'network': 96,
 'customer': 47,
 'have': 67,
 'selected': 124,
 'receivea': 118,
 '900': 14,
 'prize': 114,
 'reward': 121,
 'claim': 36,
 'call': 29,
 '09061701461': 2,
 'code': 39,
 'kl

In [86]:
vec = CountVectorizer(stop_words='english')
vec.fit(X)
vec.vocabulary_

{'freemsg': 45,
 'hey': 52,
 'darling': 38,
 'week': 118,
 'word': 124,
 'like': 62,
 'fun': 48,
 'tb': 100,
 'ok': 75,
 'xxx': 127,
 'std': 96,
 'chgs': 26,
 'send': 92,
 '50': 10,
 'rcv': 84,
 'brother': 20,
 'speak': 95,
 'treat': 105,
 'aids': 15,
 'patent': 77,
 'request': 87,
 'melle': 64,
 'oru': 76,
 'minnaminunginte': 67,
 'nurungu': 73,
 'vettam': 114,
 'set': 93,
 'callertune': 22,
 'callers': 21,
 'press': 80,
 'copy': 32,
 'friends': 46,
 'winner': 120,
 'valued': 112,
 'network': 72,
 'customer': 37,
 'selected': 91,
 'receivea': 85,
 '900': 14,
 'prize': 81,
 'reward': 88,
 'claim': 27,
 '09061701461': 2,
 'code': 29,
 'kl341': 59,
 'valid': 111,
 '12': 5,
 'hours': 55,
 'mobile': 68,
 '11': 4,
 'months': 70,
 'entitled': 43,
 'update': 108,
 'latest': 60,
 'colour': 30,
 'mobiles': 69,
 'camera': 23,
 'free': 44,
 '08002986030': 1,
 'gonna': 49,
 'home': 54,
 'soon': 94,
 'don': 42,
 'want': 115,
 'talk': 99,
 'stuff': 97,
 'anymore': 16,
 'tonight': 104,
 've': 113,
 '

In [87]:

print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['000' '08002986030' '09061701461' '100' '11' '12' '150p' '16' '20'
 '4403ldnw1a7rw18' '50' '6days' '81010' '87575' '900' 'aids' 'anymore'
 'apply' 'blessing' 'breather' 'brother' 'callers' 'callertune' 'camera'
 'cash' 'chances' 'chgs' 'claim' 'click' 'code' 'colour' 'com' 'copy'
 'cost' 'credit' 'cried' 'csh11' 'customer' 'darling' 'date' 'day' 'dbuk'
 'don' 'entitled' 'free' 'freemsg' 'friends' 'fulfil' 'fun' 'gonna'
 'granted' 'help' 'hey' 'hl' 'home' 'hours' 'http' 'info' 'jackpot'
 'kl341' 'latest' 'lccltd' 'like' 'link' 'melle' 'membership' 'message'
 'minnaminunginte' 'mobile' 'mobiles' 'months' 'net' 'network' 'nurungu'
 'oh' 'ok' 'oru' 'patent' 'pobox' 'pounds' 'press' 'prize' 'promise'
 'qjkgighjjgcbl' 'rcv' 'receivea' 'reply' 'request' 'reward' 'right'
 'searching' 'selected' 'send' 'set' 'soon' 'speak' 'std' 'stuff' 'sunday'
 'talk' 'tb' 'thank' 'times' 'today' 'tonight' 'treat' 'tsandcs' 'txt'
 'update' 'urgent' 'use' 'valid' 'valued' 've' 'vettam' 'want' 'wap'
 'watching

In [88]:
X_transformed=vec.transform(X)
X_transformed

<12x129 sparse matrix of type '<class 'numpy.int64'>'
	with 141 stored elements in Compressed Sparse Row format>

In [68]:
X=X_transformed.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [92]:
X = ["First text", "Second text", "Third text"]

# Create an instance of CountVectorizer (replace with your vectorization method)
vec = CountVectorizer()

# Convert list of strings to lowercase
X_lower = [text.lower() for text in X]

# Fit and transform your data
X_transformed = vec.fit_transform(X_lower)

# Create a DataFrame with the correct number of columns
df = pd.DataFrame(X_transformed.toarray(), columns=vec.get_feature_names_out())

print(df)

   first  second  text  third
0      1       0     1      0
1      0       1     1      0
2      0       0     1      1


In [94]:
df2 = pd.read_csv("Test_spam.csv", encoding='latin1') 
df2
from sklearn.preprocessing import LabelEncoder

In [95]:
test_numpy_array = df2.values
X_test = test_numpy_array[:, 0]
y_test = test_numpy_array[:, 1]
label_encoder = LabelEncoder()
y_test = label_encoder.fit_transform(y_test)

print("X_test:")
print(X_test)
print("y_test:")
print(y_test)


X_test:
['spam' 'ham' 'ham' 'spam' 'spam' 'ham' 'spam' 'spam' 'ham' 'ham' 'spam'
 'ham']
y_test:
[ 2  1  0 10  3  5  8  9  6  4 11  7]


In [96]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<12x4 sparse matrix of type '<class 'numpy.int64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [97]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [99]:
texts = ["First text", "Second text", "Third text"]

# Create an instance of CountVectorizer
vec = CountVectorizer()

# Fit and transform the texts
X = vec.fit_transform(texts)

# Example target variable
Y = [0, 1, 0]  # Assuming binary classification with 0 and 1 labels

# Create an instance of MultinomialNB
mnb = MultinomialNB()

# Fit the model
mnb.fit(X, Y)

# Example test data
test_texts = ["Fourth text", "Fifth text"]

# Transform the test data using the same vectorizer
X_test = vec.transform(test_texts)

# Make predictions on the test data
predictions = mnb.predict_proba(X_test)

print(predictions)

[[0.69230769 0.30769231]
 [0.69230769 0.30769231]]


In [102]:
from sklearn.metrics import accuracy_score

# Assuming y_test is the true labels and y_prediction is the predicted labels
y_test = [0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1]
y_prediction = [0, 1, 0, 1, 0, 1, 0, 1, 1, 1]  # Example predicted labels

# Make sure y_test and y_prediction have the same number of samples
if len(y_test) > len(y_prediction):
    y_test = y_test[:len(y_prediction)]
else:
    y_prediction = y_prediction[:len(y_test)]

# Calculate accuracy
acc = accuracy_score(y_test, y_prediction)

print("Accuracy:", acc)


Accuracy: 0.7
