<a href="https://colab.research.google.com/github/faizirana123/Lab-assignment/blob/main/25122_NB_Lab_Task_31_05_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score


In [ ]:
df1 = pd.read_csv("spam.csv", encoding='latin1')


In [ ]:
df1

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [59]:
df1['v1'] = df1.v1.map({'ham':0, 'spam':1})
df1

v1                                                 v2 Unnamed: 2  \
0      0  Go until jurong point, crazy.. Available only ...        NaN   
1      0                      Ok lar... Joking wif u oni...        NaN   
2      1  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      0  U dun say so early hor... U c already then say...        NaN   
4      0  Nah I don't think he goes to usf, he lives aro...        NaN   
...   ..                                                ...        ...   
5567   1  This is the 2nd time we have tried 2 contact u...        NaN   
5568   0              Will Ì_ b going to esplanade fr home?        NaN   
5569   0  Pity, * was in mood for that. So...any other s...        NaN   
5570   0  The guy did some bitching but I acted like i'd...        NaN   
5571   0                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [61]:
X= df1['v2'].to_numpy()
Y = df1['v1'].to_numpy()
Y = Y.astype('int')


In [62]:
print("X")
print(X)
print("y")
print(Y)

X
['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
 'Ok lar... Joking wif u oni...'
 "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
 ... 'Pity, * was in mood for that. So...any other suggestions?'
 "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
 'Rofl. Its true to its name']
y
[0 0 1 ... 0 0 0]


In [63]:
vec = CountVectorizer( )

In [64]:
vec.fit(X)
vec.vocabulary_

{'go': 3550,
 'until': 8030,
 'jurong': 4350,
 'point': 5920,
 'crazy': 2327,
 'available': 1303,
 'only': 5537,
 'in': 4087,
 'bugis': 1751,
 'great': 3634,
 'world': 8489,
 'la': 4476,
 'buffet': 1749,
 'cine': 2048,
 'there': 7645,
 'got': 3594,
 'amore': 1069,
 'wat': 8267,
 'ok': 5504,
 'lar': 4512,
 'joking': 4318,
 'wif': 8392,
 'oni': 5533,
 'free': 3358,
 'entry': 2949,
 'wkly': 8447,
 'comp': 2165,
 'to': 7756,
 'win': 8405,
 'fa': 3087,
 'cup': 2386,
 'final': 3207,
 'tkts': 7743,
 '21st': 411,
 'may': 4930,
 '2005': 402,
 'text': 7595,
 '87121': 784,
 'receive': 6297,
 'question': 6190,
 'std': 7230,
 'txt': 7933,
 'rate': 6242,
 'apply': 1156,
 '08452810075over18': 77,
 'dun': 2802,
 'say': 6633,
 'so': 7024,
 'early': 2823,
 'hor': 3927,
 'already': 1042,
 'then': 7640,
 'nah': 5238,
 'don': 2712,
 'think': 7660,
 'he': 3781,
 'goes': 3558,
 'usf': 8075,
 'lives': 4665,
 'around': 1207,
 'here': 3831,
 'though': 7680,
 'freemsg': 3365,
 'hey': 3841,
 'darling': 2443,
 'it

In [65]:
vec = CountVectorizer(stop_words='english')
vec.fit(X)
vec.vocabulary_

{'jurong': 4224,
 'point': 5741,
 'crazy': 2271,
 'available': 1271,
 'bugis': 1703,
 'great': 3534,
 'world': 8227,
 'la': 4349,
 'buffet': 1701,
 'cine': 1994,
 'got': 3494,
 'amore': 1051,
 'wat': 8026,
 'ok': 5343,
 'lar': 4385,
 'joking': 4192,
 'wif': 8134,
 'oni': 5369,
 'free': 3265,
 'entry': 2875,
 'wkly': 8185,
 'comp': 2110,
 'win': 8146,
 'fa': 3005,
 'cup': 2329,
 'final': 3121,
 'tkts': 7519,
 '21st': 411,
 '2005': 402,
 'text': 7388,
 '87121': 784,
 'receive': 6115,
 'question': 6010,
 'std': 7028,
 'txt': 7701,
 'rate': 6062,
 'apply': 1128,
 '08452810075over18': 77,
 'dun': 2738,
 'say': 6450,
 'early': 2757,
 'hor': 3815,
 'nah': 5092,
 'don': 2651,
 'think': 7443,
 'goes': 3458,
 'usf': 7837,
 'lives': 4535,
 'freemsg': 3272,
 'hey': 3732,
 'darling': 2386,
 'week': 8071,
 'word': 8218,
 'like': 4485,
 'fun': 3323,
 'tb': 7323,
 'xxx': 8292,
 'chgs': 1948,
 'send': 6536,
 '50': 607,
 'rcv': 6074,
 'brother': 1674,
 'speak': 6910,
 'treat': 7634,
 'aids': 985,
 'pate

In [66]:

print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out()))

['00' '000' '000pes' ... 'ûïharry' 'ûò' 'ûówell']
8404


In [67]:
X_transformed=vec.transform(X)
X_transformed

<5572x8404 sparse matrix of type '<class 'numpy.int64'>'
	with 43478 stored elements in Compressed Sparse Row format>

In [68]:
X=X_transformed.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [69]:
pd.DataFrame(X, columns=vec.get_feature_names_out())

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
5567   0    0       0             0     0     0            0            0   
5568   0    0       0             0     0     0            0            0   
5569   0    0       0             0     0     0            0            0   
5570   0    0       0             0     0     0            0            0   
5571   0    0       0             0     0     0            0            0   

      0125698789  02  ...  ó_  û_  û_thanks  ûªm  ûªt  ûªve  ûï  ûïharry  ûò  \
0              0   0  ...   0   0         0    0    0     0   0        0   0   
1              0   0  ...   0   0         0    0    0     0   0        0   0   
2              0   0  ...   0   0         0    0    0     0   0        0   0   
3              0   0  ...   0   0         0    0    0     0   0        0   0   
4              0   0  ...   0   0         0    0    0     0   0        0   0   
...          ...  ..  ...  ..  ..       ...  ...  ...   ...  ..      ...  ..   
5567           0   0  ...   0   0         0    0    0     0   0        0   0   
5568           0   0  ...   0   0         0    0    0     0   0        0   0   
5569           0   0  ...   0   0         0    0    0     0   0        0   0   
5570           0   0  ...   0   0         0    0    0     0   0        0   0   
5571           0   0  ...   0   0         0    0    0     0   0        0   0   

      ûówell  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
5567       0  
5568       0  
5569       0  
5570       0  
5571       0  

[5572 rows x 8404 columns]

In [73]:
df2 = pd.read_csv("spam.csv", encoding='latin1') 
df2
from sklearn.preprocessing import LabelEncoder

In [74]:
test_numpy_array = df2.values
X_test = test_numpy_array[:, 0]
y_test = test_numpy_array[:, 1]
label_encoder = LabelEncoder()
y_test = label_encoder.fit_transform(y_test)

print("X_test:")
print(X_test)
print("y_test:")
print(y_test)


X_test:
['ham' 'ham' 'spam' ... 'ham' 'ham' 'ham']
y_test:
[1079 3101 1000 ... 3286 3901 3409]


In [75]:
X_test_transformed=vec.transform(X_test)
X_test_transformed

<5572x8404 sparse matrix of type '<class 'numpy.int64'>'
	with 5572 stored elements in Compressed Sparse Row format>

In [76]:
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [77]:
mnb=MultinomialNB()

mnb.fit(X,Y)

mnb.predict_proba(X_test)

array([[0.93945225, 0.06054775],
       [0.93945225, 0.06054775],
       [0.60808735, 0.39191265],
       ...,
       [0.93945225, 0.06054775],
       [0.93945225, 0.06054775],
       [0.93945225, 0.06054775]])

In [78]:
y_prediction = mnb.predict(X_test)


acc = accuracy_score(y_test, y_prediction)


print("Accuracy:", acc)


Accuracy: 0.00017946877243359656
